### ISSUE TITLE
First it can't find selenium-chromedriver, then there is an unexpected identifier. 

### ISSUE THREAD

**Issue by neatville** [slamdata/purescript-webdriver#57]
On Windows 10, I installed it with `bower install purescript-webdriver`. Then it gives me the first error I mentioned, so I did `npm install selenium-chromedriver`. Now it gives me this error.  

```
  async execute(command) {
        ^^^^^^^
SyntaxError: Unexpected identifier
```
By any chance, could the installation instructions, or anything else use any updating?

**Comment by kRITZCREEK** [comment]
Try these node dependencies as specified in the [`package.json`](https://github.com/slamdata/purescript-webdriver/blob/master/package.json#L8-L11) of this project.
```
  "dependencies": {
    "chromedriver": "^2.29.0",
    "selenium-webdriver": "3.4.0"
},
```

**Comment by neatville** [comment]
I decided to retry from scratch on Linux.. after doing `git clone...`, `bower install`, `pulp build`, then `pulp test`, I still get very similar errors.   
```
* Build successful.
* Running tests...
module.js:557
    throw err;
    ^

Error: Cannot find module 'chromedriver'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/purescript-webdriver/output/Selenium/foreign.js:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
* ERROR: Subcommand terminated with exit code 1

```

**Comment by garyb** [comment]
Did you `npm install` too? chromedriver is an npm dependency, not a bower dependency.

**Comment by neatville** [comment]
Thanks @garyb, that worked. 
These two issues would be separate, but when changing the browser to `FireFox`, it went to Google with the firefox browser, but I did get this error.  
```
* Building project in /path/to/purescript-webdriver
Compiling Test.Main
* Build successful.
* Running tests...
/path/to/purescript-webdriver/output/Control.Monad.Aff/foreign.js:513
                throw util.fromLeft(step);
                ^

InvalidArgumentError: Could not convert 'text' to string

```
The chrome browser was tracking my location, which isn't surprising. I found a way to stop that when using selenium with Python, but the documentation for `purescript-webdriver` doesn't seem to include this.  More familiarity with node and the JavaScript ecosystem might be assumed too, something I'm not used to.  
Anyways, thanks again.
